jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_13_x:
        node_version: 13.x
      node_12_x:
        node_version: 12.x
      node_11_x:
        node_version: 11.x
      node_10_x:
        node_version: 10.x
      # Lowest supported version.
      node_10_12:
        node_version: 10.12.0
    maxParallel: 5
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js
  - bash: npm i
    displayName: Install dependencies
  - bash: npm run ci-lint
    displayName: Check linting
  - bash: npm run ci-test-cov
    displayName: Run tests with code coverage
